### ISSUE TITLE
[Invoice API] Support multiple items for 1 Invoice

### ISSUE THREAD

**Issue by dylan751** [dylan751/ramen#58]
## Why
- 1 invoice should includes multiple items

## Tasks
- [x] Migrate DB: Add `invoice_items` table, update `invoice` table
- [x] Add/update DTOs
- [x] Update APIs
  - [x] Create Invoice
  - [x] Update Invoice
  - [x] Get 1 Invoice
  - [x] Get all Invoices
  - [x] Delete Invoice
